<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<fndatabase>
	<fn_settings>
		<varname>use_urlserverpath</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>sitename</varname>
		<varvalue>dbcave</varvalue>
		<defaultvalue>Flatnux-NEXT</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_title</varname>
		<varvalue>Portale Speleo</varvalue>
		<defaultvalue>Flatnux CMS</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_subtitle</varname>
		<varvalue>www.flatnux.org</varvalue>
		<defaultvalue>www.flatnux.org</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>keywords</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>languages</varname>
		<varvalue>it,en</varvalue>
		<defaultvalue>en</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>theme</varname>
		<varvalue>openkis</varvalue>
		<defaultvalue>default</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>controlcenter_theme</varname>
		<varvalue>classic</varvalue>
		<defaultvalue>classic</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>switchtheme</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>siteurl</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>site_email_address</varname>
		<varvalue>nobody@site_email_address.set</varvalue>
		<defaultvalue>nobody@site_email_address.set</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>log_email_address</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_compress_gzip</varname>
		<varvalue>1</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>home_section</varname>
		<varvalue>home</varvalue>
		<defaultvalue>home</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>jet_lag</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>showaccesskey</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_log_email</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_mod_rewrite</varname>
		<varvalue>0</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>links_mode</varname>
		<varvalue>folders</varvalue>
		<defaultvalue>html</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_registration</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>username_is_email</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>registration_by_email</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>remember_login</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_captcha</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>htmleditor</varname>
		<varvalue>ckeditor4</varvalue>
		<defaultvalue>ckeditor4</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>enable_online_administration</varname>
		<varvalue>1</varvalue>
		<defaultvalue>1</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>credits</varname>
		<varvalue>Powered by &lt;a href='http://www.flatnux.org'&gt;Flatnux&lt;/a&gt;</varvalue>
		<defaultvalue>Powered by &lt;a href='http://www.flatnux.org'&gt;Flatnux&lt;/a&gt;</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>maintenance</varname>
		<varvalue>0</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>url_update</varname>
		<varvalue>http://www.flatnux.altervista.org/updates/FLATNUXSTABLE</varvalue>
		<defaultvalue>http://www.flatnux.altervista.org/updates/FLATNUXSTABLE</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>use_cache</varname>
		<varvalue>1</varvalue>
		<defaultvalue>0</defaultvalue>
	</fn_settings>
	<fn_settings>
		<varname>timezone</varname>
		<varvalue></varvalue>
		<defaultvalue></defaultvalue>
	</fn_settings>
</fndatabase>