-- OpenKIS Demo Cave Data
-- This file contains a sample cave record for demonstration purposes

INSERT INTO `ctl_caves` (
    `code`,
    `name`,
    `synonyms`,
    `firstreference`,
    `country`,
    `regione`,
    `provincia`,
    `comune`,
    `localita`,
    `mount`,
    `velley`,
    `geologicalformation`,
    `lithology`,
    `lenght_total`,
    `lenght_planimetric`,
    `depth_positive`,
    `depth_negative`,
    `depth_total`,
    `latitude_txt`,
    `longitude_txt`,
    `coordinates_type`,
    `elevation`,
    `location_evaluation`,
    `archeological`,
    `marine`,
    `lake`,
    `environmentalrisk`,
    `tourist`,
    `closed`,
    `destroyed`,
    `hydrology`,
    `trend`,
    `practicability`,
    `description`,
    `itinerary`,
    `geology`,
    `history`,
    `latitude`,
    `longitude`,
    `recordinsert`,
    `username`
) VALUES (
    'DEMO1',
    'GROTTA DEMO',
    'GROTTA DIMOSTRATIVA; CAVERNA ESEMPIO',
    'OpenKIS Team',
    'Italy',
    'LIGURIA',
    'GE',
    'GENOVA',
    'MONTE EXAMPLE',
    'MONTE FASCE',
    'VAL BISAGNO',
    '',
    'Calcare marnoso',
    '150',
    '120',
    '10',
    '45',
    '55',
    '44.4234',
    '8.9876',
    'WGS84',
    '450',
    'Coordinate GPS con precisione 3m',
    'N',
    'N',
    'N',
    'N',
    '',
    '',
    '',
    'dry',
    'Orizzontale con tratti in discesa',
    'Facile, adatta a principianti',
    'Grotta dimostrativa per testare il sistema OpenKIS. La cavita si sviluppa orizzontalmente per circa 120 metri con un dislivello complessivo di 55 metri. L''ingresso si apre su una parete rocciosa ed e facilmente individuabile. All''interno si alternano ambienti ampi e cunicoli, con belle concrezioni calcaree.',
    'Dalla localita Monte Example, seguire il sentiero segnato fino alla parete rocciosa. L''ingresso e visibile sulla destra.',
    'La grotta si e formata in calcari marnosi del Cretaceo superiore. Presenta fenomeni di carsismo attivo con stalattiti e stalagmiti in formazione.',
    'Conosciuta fin dall''antichita, fu esplorata sistematicamente nel 1950 dal Gruppo Speleologico Locale. Nel 2024 e stata inserita come esempio nel sistema OpenKIS.',
    44.4234,
    8.9876,
    NOW(),
    'admin'
);

-- Optional: Insert a sample coordinate type if not exists
INSERT IGNORE INTO `ctl_coordinatestypes` (`coordinates_type`) VALUES ('WGS84');
