<?xml version="1.0" encoding="UTF-8"?>
<?php exit(0);?>
<tables>
	<field>
		<name>unirecid</name>
		<primarykey>1</primarykey>
		<extra>autoincrement</extra>
		<frm_show>0</frm_show>
	</field>
	<field>
		<name>insert</name>
		<type>string</type>
		<defaultvalue></defaultvalue>
		<frm_show>0</frm_show>
	</field>
	<field>
		<name>username</name>
		<type>string</type>
		<frm_show>0</frm_show>
		<frm_required>1</frm_required>
	</field>
	<field>
		<name>title</name>
		<frm_it>Titolo</frm_it>
		<frm_i18n>title</frm_i18n>
		<type>string</type>
		<frm_required>1</frm_required>
	</field>
	<field>
		<name>comment</name>
		<frm_it>Commento</frm_it>
		<frm_i18n>comment</frm_i18n>
		<type>text</type>
		<frm_rows>10</frm_rows>
		<frm_required>1</frm_required>
		<frm_cols>80</frm_cols>
	</field>
	<field>
		<name>unirecidrecord</name>
		<frm_show>0</frm_show>
	</field>
</tables>